### ISSUE TITLE
BlockingLimiter: java.lang.ArithmeticException: long overflow after updating from 0.1.1 to 0.1.2

### ISSUE THREAD

**Issue by PascalSchumacher** [Netflix/concurrency-limits#86]
After updating from `0.1.1` to `0.1.2` I get:

>java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892)
	at java.time.Duration.toMillis(Duration.java:1171)
	at com.netflix.concurrency.limits.limiter.BlockingLimiter.tryAcquire(BlockingLimiter.java:70)
	at com.netflix.concurrency.limits.limiter.BlockingLimiter.acquire(BlockingLimiter.java:87)

The same exception occurs when I use version `0.1.4`.

**Comment by PascalSchumacher** [comment]
Thank you very much for the quick fix! 👍
